$ANSIBLE_VAULT;1.1;AES256
38386361336132336338313037336166646639323730373130356535663864613531366566656461
3639633462373562323864626239656465663631306663330a303466386632636362313232633964
39643835313165626131663766343130666138353531626334373231313234313738626665373035
3234383864326464350a396633376465316639643362336565633963643964386436616337653338
66663832356466363030336562393038396561323135333666376463653230303665663062393236
33373264373862353365653033623263313234616634323863323065646332643962663035313835
353534343464653763393934613534353633
